name: Go Test

on:
  push:
    branches: [ dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
        run:
            working-directory: web-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Run tests
        run: go test ./...
